controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    lift_position_controller:
      type: position_controllers/JointGroupPositionController
      joints:
        - lift_joint
