<?xml version="1.0"?>
<package format="3">
  <name>hand_tracker_control</name>
  <version>0.0.1</version>
  <description>Hand tracking robot control</description>
  <maintainer email="azif@example.com">Azif</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_python</buildtool_depend>
  <depend>rclpy</depend>
  <depend>trajectory_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>std_msgs</depend>
  <depend>sensor_msgs</depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
